### ISSUE TITLE
Requests params

### ISSUE THREAD

**Issue by cipherbullet** [behnamhatami/stock#2]
Hi, there are some params like h, r, c and etc in params that you use in your requests.
what did they mean? and how should use them? and what they can be?

**Comment by behnamhatami** [comment]
Hi,
There isn't any documentation in tsetmc about these params, but I tried to find it by try and error.
g -> group.id
i -> share.id
t -> type
s -> no idea
Top -> head of the result
A -> ?
h, r -> they refer to time or transaction number or something, but it is not obvious what are the unit
but if you set it to zero you will get all the data not difference from the last fetch
c -> ?
