### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by morysam96** [behnamhatami/stock#3]
اول پروژه میاره و اجازه مایگریت نمیده

File "C:\Python38\lib\logging\handlers.py", line 892, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'

**Comment by behnamhatami** [comment]
من syslog رو برای سیستم‌های غیر لینوکسی غیر فعال کردم.
خودم سیستم ویندوزی ندارم ولی چک کنید ببینید مشکل حل شده یا نه.
