### ISSUE TITLE
ConnectionAbortedError

### ISSUE THREAD

**Issue by morysam96** [behnamhatami/stock#4]
سلام 
ممنون بابت پاسخ به مشکل قبلی شما کدتون اجرا میشه به نطرم کدتون چندجا مشکل داره.

> را ایراد میگیره که در پایگاه داده اس کیو ال نمی توانی اضافه کنی. JSONField  در مورد مایگریشن که وقنی مایگریت میکنی کلاس  
من رفتم پایگاه داده پستگره را ایجاد و مایگریت کردم درست شد ولی دیگه بعدش در پنل ادمین این ارور میاره
djangoConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

ممنون

**Comment by behnamhatami** [comment]
Hi,
I suggest you to upgrade your Django version or install pip packages from requirement.txt file.
Due to Django 3.1 [release note](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends),  all backends support json fields.
