### ISSUE TITLE
migrate

### ISSUE THREAD

**Issue by morysam96** [behnamhatami/stock#6]
python manage.py migrate:
crawler.Share: (fields.E180) SQLite does not support JSONFields.

**Comment by behnamhatami** [comment]
Hi,
I suggest you to upgrade your Django version or install pip packages from requirement.txt file.
Due to Django 3.1 [release note](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends), all backends support json fields.
